---
- name: Bootstrap basic
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  collections:
    - devsec.hardening
  roles:
    - cloudalchemy.node_exporter
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
        sleep: 5
  tasks:
    - name: Install common packages
      apt:
        name: "{{ common_packages }}"
        state: "present"
        install_recommends: false
    - name: Enable logrotate hourly
      file:
        src: /etc/cron.daily/logrotate
        dest: /etc/cron.hourly/logrotate
        state: link
    - name: Configure logrotate
      copy:
        src: "files/logrotate.d/{{ item }}"
        dest: "/etc/logrotate.d/{{ item }}"
        owner: root
        group: root
        mode: 0755
      loop:
        - rsyslog
    - name: Deploy extra authorized keys
      authorized_key:
        user: "{{ item.value.user|default(ansible_ssh_user) }}"
        key: "{{ item.value.key }}"
        state: present
        key_options: "{{ item.value.key_options|default(omit) }}"
        comment: "{{ item.value.comment|default(omit) }}"
      loop: "{{ extra_authorized_keys|default({})|dict2items }}"

    - name: Deploy /etc/resolv.conf
      template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
        mode: 0644
        owner: root
        group: root
      notify: restart networking

    - name: Ensure resolv.conf is immutable.
      file:
        path: /etc/resolv.conf
        attr: +i
      register: resolv_file
      changed_when: "'i' not in resolv_file.diff.before.attributes"

    - name: Make sure debian.example.com is not present in /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '127.0.1.1\s*debian.example.com'
