---
- name: Deploy grafana service auto annotations toolkit
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  gather_facts: false
  handlers:
    - name: daemon-reload
      systemd:
        daemon_reload: true
  tasks:
    - name: Deploy grafana annotations script
      template:
        src: grafana-annotation.sh.j2
        dest: "/usr/local/bin/grafana-annotation.sh"
        owner: root
        group: root
        mode: 0755  # I'm lazy
