---
- name: Install loadbalancer
  hosts: meta-role_lb,meta-role_patroni_lb,meta-subrole_prometheus
  any_errors_fatal: true
  become: true
  become_user: root
  tasks:
    - name: Install haproxy & co.
      apt:
        name:
          - haproxy
          - haproxyctl
          - hatop
        state: present
  roles:
    - griggheo.consul-template
    - bdellegrazie.haproxy_exporter
