---
private_ip: "{{ ansible_all_ipv4_addresses | ipaddr('10.0.0.0/8') | first }}"
common_packages:
  - acl
  - apt-transport-https
  - ca-certificates
  - conntrack
  - cron
  - curl
  - diffutils
  - dnsutils
  - dstat
  - git
  - gnupg
  - htop
  - iftop
  - iotop
  - net-tools
  - nmap
  - sysstat
  - telnet

ansible_ssh_user: debian

sysctl_config:
  vm.swappiness: 10
  net.core.somaxconn: 16384
  net.ipv4.tcp_max_syn_backlog: 30000
  net.ipv4.tcp_max_tw_buckets: 2000000
  net.ipv4.tcp_tw_reuse: 1

  net.ipv4.conf.eth0.arp_ignore: 1
  net.ipv4.conf.eth1.arp_ignore: 1

  # arp_announce : 2 - Always use the best local address for this
  net.ipv4.conf.eth0.arp_announce: 2
  net.ipv4.conf.eth1.arp_announce: 2

  # Disable Syn cookies
  net.ipv4.tcp_syncookies: 0

  # No arp between all NICs
  net.ipv4.conf.all.arp_filter: 1
  net.ipv4.conf.default.arp_filter: 1
  net.ipv4.conf.lo.arp_filter: 1
  net.ipv4.conf.eth0.arp_filter: 1
  net.ipv4.conf.eth1.arp_filter: 1

  # TCP tuning
  # cloudflare uses this for balancing latency and throughput
  # https://blog.cloudflare.com/the-story-of-one-latency-spike/
  net.ipv4.tcp_rmem: 4096 1048576 2097152
  net.ipv4.tcp_wmem: 4096 65536 16777216

  # TCP timeout
  net.ipv4.tcp_fin_timeout: 10
  net.ipv4.tcp_keepalive_intvl: 30
  net.ipv4.tcp_keepalive_probes: 5

  fs.file-max: 1200000
  net.ipv4.netfilter.ip_conntrack_max: 800000

  # Neighbour table overflow protection
  net.ipv4.neigh.default.gc_thresh1: 65536
  net.ipv4.neigh.default.gc_thresh2: 131072
  net.ipv4.neigh.default.gc_thresh3: 262144

  # http://www.nateware.com/linux-network-tuning-for-2013.html
  # Increase Linux autotuning TCP buffer limits
  # Set max to 16MB for 1GE and 32M (33554432) or 54M (56623104) for 10GE
  # Don't set tcp_mem itself! Let the kernel scale it based on RAM.
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.core.rmem_default: 16777216
  net.core.wmem_default: 16777216
  net.core.optmem_max: 40960
  # Also increase the max packet backlog
  net.core.netdev_budget: 50000
  net.core.netdev_max_backlog: 100000
  # Make room for more TIME_WAIT sockets due to more clients,
  # and allow them to be reused if we run out of sockets
  # Disable TCP slow start on idle connections
  net.ipv4.tcp_slow_start_after_idle: 0
