systemd_drop_ins:
  - name: "node_exporter"
    override_filename: "grafana_annotation.conf"
    service_overrides:
      Service:
        ExecStartPre: "-/usr/local/bin/grafana-annotation.sh node_exporter starting"
        ExecStopPost: "-/usr/local/bin/grafana-annotation.sh node_exporter stopping"
  - name: "memcached"
    overrid_filename: "tuning.cong"
    service_overrides:
      Service:
        LimitNOFILE: 1048576
