---
cortex_version: 1.10.0
cortex_arch: amd64

cortex_package_filename: "cortex-{{ cortex_version }}_{{ cortex_arch }}.deb"
cortex_base_url: "https://github.com/cortexproject/cortex"
cortex_url: "{{ cortex_base_url }}/releases/download/v{{ cortex_version }}/{{ cortex_package_filename }}"

cortex_systemd_override_directory: /etc/systemd/system/cortex.service.d/
cortex_systemd_override:
  Service:
    LimitNOFILE: 1048576

# See cortex -modules
cortex_target: all
cortex_auth_enabled: false
cortex_http_prefix: /api/prom

cortex_http_listen_port: 9009
cortex_http_listen_address: 0.0.0.0
cortex_grpc_listen_port: 9095
cortex_grpc_listen_address: 0.0.0.0


# Valid levels: [debug, info, warn, error]
cortex_log_level: info
cortex_configuration_file: /etc/cortex/config.yml
cortex_custom_args: ""
cortex_restart_on_upgrade: true

cortex_root_directory: "/var/lib/cortex"
cortex_wal_directory: "{{ cortex_root_directory }}/wal"
cortex_boltdb_directory: "{{ cortex_root_directory }}/index"
cortex_chunk_directory: "{{ cortex_root_directory }}/chunks"
cortex_rules_directory: "{{ cortex_root_directory }}/rules"
cortex_data_directory: "{{ cortex_root_directory }}/data"
cortex_tsdb_directory: "{{ cortex_root_directory }}/tsdb"
cortex_active_query_tracker_directory: "{{ cortex_root_directory }}/active-query-tracker"
cortex_tsdb_sync_directory: "{{ cortex_root_directory }}/tsdb-sync"

cortex_tokens_file_path: "{{ cortex_root_directory }}/tokens"

cortex_api: {}
cortex_tenant_federation: {}
cortex_grpc_client_config: {}
cortex_kv_store_consul_config: {}
cortex_kv_store_etcd: {}
cortex_kv_store_multi: {}
cortex_schema: {}
cortex_ingester_client: {}
cortex_alertmanager: {}
cortex_alertmanager_storage: {}
cortex_blocks_storage: {}
cortex_chunk_store: {}
cortex_compactor: {}
cortex_configs: {}
cortex_distributor: {}
cortex_flusher: {}
cortex_frontend: {}
cortex_frontend_worker: {}
cortex_ingester: {}
cortex_limits: {}
cortex_memberlist: {}
cortex_purger: {}
cortex_querier: {}
cortex_query_range: {}
cortex_query_scheduler: {}
cortex_ruler: {}
cortex_ruler_storage: {}
cortex_server: {}
cortex_storage: {}
cortex_store_gateway: {}
cortex_table_manager: {}
cortex_runtime_config: {}
cortex_prealloc: {}

cortex_extra_envvars: {}
