---
grafana_security:
  admin_user: "{{ grafana_admin_user }}"
  admin_password: "{{ grafana_admin_password }}"

grafana_datasources:
  - name: "Prometheus"
    uid: prometheus
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus-0.node.consul:9090"
    isDefault: true
    jsonData:
      disableMetricsLookup: false
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST

  - name: "VictoriaMetrics"
    uid: victoriametrics
    type: "prometheus"
    access: "proxy"
    url: "http://ro.victoriametrics.service.dc1.consul:8481/select/0/prometheus"

  - name: "promscale"
    uid: promscale
    type: "prometheus"
    access: "proxy"
    url: "http://ro.promscale.service.dc1.consul:9201"

  - name: "cortex-all-tenants"
    uid: cortex-all-tenants
    type: "prometheus"
    access: "proxy"
    url: "http://ro.cortex.service.dc1.consul:9090/prometheus"
    jsonData:
      disableMetricsLookup: false
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'tenant-1|tenant-2|tenant-3'

  - name: "cortex-tenant-1"
    uid: cortex-tenant-1
    type: "prometheus"
    access: "proxy"
    url: "http://ro.cortex.service.dc1.consul:9090/prometheus"
    jsonData:
      disableMetricsLookup: false
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'tenant-1'

  - name: "cortex-tenant-2"
    uid: cortex-tenant-2
    type: "prometheus"
    access: "proxy"
    url: "http://ro.cortex.service.dc1.consul:9090/prometheus"
    jsonData:
      disableMetricsLookup: false
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'tenant-2'

  - name: "cortex-tenant-3"
    uid: cortex-tenant-3
    type: "prometheus"
    access: "proxy"
    url: "http://ro.cortex.service.dc1.consul:9090/prometheus"
    jsonData:
      disableMetricsLookup: false
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'tenant-3'

  - name: "timescaledb"
    uid: timescaledb
    type: "postgres"
    sslmode: "require"
    access: "proxy"
    url: "ro.timescaledb.service.dc1.consul:4000"
    database: "timescale"
    user: "timescale"
    password: "timescale"
    jsonData:
      sslmode: require
      timescaledb: true
      postgresVersion: 1200

  - name: "loki"
    uid: loki
    type: "loki"
    access: "proxy"
    url: "http://loki.service.dc1.consul:3100"

  - access: proxy
    name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo.service.dc1.consul:3200

grafana_plugins:
  - grafana-worldmap-panel
  - grafana-piechart-panel
  - digiapulssi-breadcrumb-panel

grafana_dashboards:
  # Prometheus Node Exporter Full
  - dashboard_id: 1860
    revision_id: 21
    datasource: Prometheus
  # Prometheus - cluster
  - dashboard_id: 11176
    revision_id: 8
    datasource: Prometheus
  # Postgres Overview
  - dashboard_id: 455
    revision_id: 2
    datasource: Prometheus
  # HAproxy Servers | HAproxy
  - dashboard_id: 367
    revision_id: 3
    datasource: Prometheus
  # HAproxy Backend | HAproxy
  - dashboard_id: 364
    revision_id: 3
    datasource: Prometheus
  # HAproxy Frontend | HAproxy
  - dashboard_id: 361
    revision_id: 3
    datasource: Prometheus
  # Prometheus 2.0 Overview
  - dashboard_id: 3662
    revision_id: 2
    datasource: Prometheus
  # Prometheus memcached
  - dashboard_id: 37
    revision_id: 1
    datasource: Prometheus

grafana_dashboards_dir: files/grafana/dashboards/

grafana_tracing:
  address: tempo.service.dc1.consul:6831

grafana_feature_toggles:
  - tempoSearch
